### ISSUE TITLE
Organization Description

### ISSUE THREAD

**Issue by azrdn** [C242-PS121/.github#1]
kalo ada waktu luang tolong ganti lorem ipsum nya ya :shipit:

**Comment by fahrulrozi11** [comment]
lorem yang di ganti cuma yang di README,md doang kan

Pada Sel, 26 Nov 2024 pukul 18.01 Azis Ramadhan ***@***.***>
menulis:

**Comment by azrdn** [comment]
Yoi

**Comment by azrdn** [comment]
Thank you roz
